### ISSUE TITLE
CDK Deploy fails due to issue with GraphQL schema

### ISSUE THREAD

**Issue by hom-bahrani** [hom-bahrani/cdk-appsync-cognito-dynamodb#1]
There's an issue with the GraphQL schema that is preventing the CDK stack from being deployed. This needs to be debugged  further e.g. isolate the issue with a library like graphql-yoga and test with its UI tool. Here is the synthesised Cloudformation template - `ApiSchema510EECD7` is failing to build.

```yaml
Resources:
  coursesappuserpool6C3C8587:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      EmailVerificationMessage: The verification code to your new account is {####}
      EmailVerificationSubject: Verify your new account
      Schema:
        - Mutable: true
          Name: email
          Required: true
      SmsVerificationMessage: The verification code to your new account is {####}
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: The verification code to your new account is {####}
        EmailSubject: Verify your new account
        SmsMessage: The verification code to your new account is {####}
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/courses-app-user-pool/Resource
  UserPoolClient2F5918F7:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: coursesappuserpool6C3C8587
      AllowedOAuthFlows:
        - implicit
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - profile
        - phone
        - email
        - openid
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - https://example.com
      SupportedIdentityProviders:
        - COGNITO
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/UserPoolClient/Resource
  ApiF70053CD:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      AuthenticationType: AMAZON_COGNITO_USER_POOLS
      Name: courses-appsync-api
      UserPoolConfig:
        AwsRegion:
          Ref: AWS::Region
        DefaultAction: ALLOW
        UserPoolId:
          Ref: coursesappuserpool6C3C8587
      XrayEnabled: true
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/Resource
  ApiSchema510EECD7:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId:
        Fn::GetAtt:
          - ApiF70053CD
          - ApiId
      Definition: >-
        input CreateUserInput {
          id: ID!
          name: String!
          email: String!
          Quests: [Quest]!
          premiumMember: Boolean!
        }


        input UpdateUserInput {
          id: ID!
          name: String
          email: String
          currentQuests: [Quest]
          premiumMember: Boolean
        }


        input QuestInput {
          id: ID!
          name: String!
          description: String!
          completed: Boolean!
          lessonList: [Lesson!]!
        }


        input LessonInput {
          id: ID!
          name: String
          heading: String
          content: String
          codeSnippet: String
          imageURL: String
          audioURL: String
          videoURL: String
          assignmentPassed: Boolean!
          leassonCompleted: Boolean!
        }


        type User {
          id: ID!
          name: String!
          email: String!
          currentQuests: [Quest]!
          premiumMember: Boolean!
        }


        type Quest {
          id: ID!
          name: String!
          description: String!
          completed: Boolean!
          lessonList: [Lesson!]!
        }


        type Lesson {
          id: ID!
          name: String
          heading: String
          content: String
          codeSnippet: String
          imageURL: String
          audioURL: String
          videoURL: String
          assignmentPassed: Boolean!
          leassonCompleted: Boolean!
        }


        type Query {
          getUserById(userId: String!): User
          getQuestDirectory: [Quest!]!
          getQuestById(questId: String!): Quest
          getLessonById(lessonId: String!): Lesson
        }


        type Mutation {
          createUser(data: CreateUserInput!): User!
          updateUser(data: UpdateUserInput!): User!
          deleteUser(userID: String!): User!
          createQuest(data: QuestInput!): Quest!
          updateQuest(data: QuestInput!): Quest!
          deleteQuest(questID: String!): Quest!
          createLesson(data: LessonInput!): Lesson!
          updateLesson(data: LessonInput!): Lesson!
          deleteLesson(lessonID: String!): Lesson!
        }


        type Subscription {
          onCreateUser: User
            @aws_subscribe(mutations: ["createUser"])
          onUpdateUser: User
            @aws_subscribe(mutations: ["updateUser"])
          onDeleteUser: String
            @aws_subscribe(mutations: ["deleteUser"])
          onCreateQuest: Quest
            @aws_subscribe(mutations: ["createQuest"])
          onUpdateQuest: Quest
            @aws_subscribe(mutations: ["updateQuest"])
          onDeleteQuest: Quest
            @aws_subscribe(mutations: ["deleteQuest"])
          onCreateLesson: Lesson
            @aws_subscribe(mutations: ["createLesson"])
          onUpdateLesson: Lesson
            @aws_subscribe(mutations: ["updateLesson"])
          onDeleteLesson: Lesson
            @aws_subscribe(mutations: ["deleteLesson"])
        }
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/Schema
  ApilambdaDatasourceServiceRole2CA75790:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/lambdaDatasource/ServiceRole/Resource
  ApilambdaDatasourceServiceRoleDefaultPolicy3A97E34D:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - AppSyncCoursesHandlerE55512B6
                - Arn
        Version: "2012-10-17"
      PolicyName: ApilambdaDatasourceServiceRoleDefaultPolicy3A97E34D
      Roles:
        - Ref: ApilambdaDatasourceServiceRole2CA75790
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/lambdaDatasource/ServiceRole/DefaultPolicy/Resource
  ApilambdaDatasource2C776EE2:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId:
        Fn::GetAtt:
          - ApiF70053CD
          - ApiId
      Name: lambdaDatasource
      Type: AWS_LAMBDA
      LambdaConfig:
        LambdaFunctionArn:
          Fn::GetAtt:
            - AppSyncCoursesHandlerE55512B6
            - Arn
      ServiceRoleArn:
        Fn::GetAtt:
          - ApilambdaDatasourceServiceRole2CA75790
          - Arn
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/lambdaDatasource/Resource
  ApiQuerygetUserByIdResolverA9EF1A30:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - ApiF70053CD
          - ApiId
      FieldName: getUserById
      TypeName: Query
      DataSourceName: lambdaDatasource
      Kind: UNIT
    DependsOn:
      - ApilambdaDatasource2C776EE2
      - ApiSchema510EECD7
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/QuerygetUserByIdResolver/Resource
  ApiQuerygetQuestDirectoryResolver4AAF9FA8:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - ApiF70053CD
          - ApiId
      FieldName: getQuestDirectory
      TypeName: Query
      DataSourceName: lambdaDatasource
      Kind: UNIT
    DependsOn:
      - ApilambdaDatasource2C776EE2
      - ApiSchema510EECD7
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/QuerygetQuestDirectoryResolver/Resource
  ApiQuerygetQuestByIdResolver3378943A:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - ApiF70053CD
          - ApiId
      FieldName: getQuestById
      TypeName: Query
      DataSourceName: lambdaDatasource
      Kind: UNIT
    DependsOn:
      - ApilambdaDatasource2C776EE2
      - ApiSchema510EECD7
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/QuerygetQuestByIdResolver/Resource
  ApiQuerygetLessonByIdResolver84DCDECE:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - ApiF70053CD
          - ApiId
      FieldName: getLessonById
      TypeName: Query
      DataSourceName: lambdaDatasource
      Kind: UNIT
    DependsOn:
      - ApilambdaDatasource2C776EE2
      - ApiSchema510EECD7
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/QuerygetLessonByIdResolver/Resource
  ApiMutationcreateUserResolver1A5C22BA:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - ApiF70053CD
          - ApiId
      FieldName: createUser
      TypeName: Mutation
      DataSourceName: lambdaDatasource
      Kind: UNIT
    DependsOn:
      - ApilambdaDatasource2C776EE2
      - ApiSchema510EECD7
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/MutationcreateUserResolver/Resource
  ApiMutationupdateUserResolverC1D8B7A0:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - ApiF70053CD
          - ApiId
      FieldName: updateUser
      TypeName: Mutation
      DataSourceName: lambdaDatasource
      Kind: UNIT
    DependsOn:
      - ApilambdaDatasource2C776EE2
      - ApiSchema510EECD7
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/MutationupdateUserResolver/Resource
  ApiMutationdeleteUserResolver08C44CED:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - ApiF70053CD
          - ApiId
      FieldName: deleteUser
      TypeName: Mutation
      DataSourceName: lambdaDatasource
      Kind: UNIT
    DependsOn:
      - ApilambdaDatasource2C776EE2
      - ApiSchema510EECD7
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/MutationdeleteUserResolver/Resource
  ApiMutationcreateQuestResolverDB4CDDF7:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - ApiF70053CD
          - ApiId
      FieldName: createQuest
      TypeName: Mutation
      DataSourceName: lambdaDatasource
      Kind: UNIT
    DependsOn:
      - ApilambdaDatasource2C776EE2
      - ApiSchema510EECD7
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/MutationcreateQuestResolver/Resource
  ApiMutationupdateQuestResolverC7424422:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - ApiF70053CD
          - ApiId
      FieldName: updateQuest
      TypeName: Mutation
      DataSourceName: lambdaDatasource
      Kind: UNIT
    DependsOn:
      - ApilambdaDatasource2C776EE2
      - ApiSchema510EECD7
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/MutationupdateQuestResolver/Resource
  ApiMutationdeleteQuestResolver62403019:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - ApiF70053CD
          - ApiId
      FieldName: deleteQuest
      TypeName: Mutation
      DataSourceName: lambdaDatasource
      Kind: UNIT
    DependsOn:
      - ApilambdaDatasource2C776EE2
      - ApiSchema510EECD7
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/MutationdeleteQuestResolver/Resource
  ApiMutationcreateLessonResolver3D7129B6:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - ApiF70053CD
          - ApiId
      FieldName: createLesson
      TypeName: Mutation
      DataSourceName: lambdaDatasource
      Kind: UNIT
    DependsOn:
      - ApilambdaDatasource2C776EE2
      - ApiSchema510EECD7
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/MutationcreateLessonResolver/Resource
  ApiMutationupdateLessonResolverDBCA0077:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - ApiF70053CD
          - ApiId
      FieldName: updateLesson
      TypeName: Mutation
      DataSourceName: lambdaDatasource
      Kind: UNIT
    DependsOn:
      - ApilambdaDatasource2C776EE2
      - ApiSchema510EECD7
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/MutationupdateLessonResolver/Resource
  ApiMutationdeleteLessonResolverD15F18EF:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
          - ApiF70053CD
          - ApiId
      FieldName: deleteLesson
      TypeName: Mutation
      DataSourceName: lambdaDatasource
      Kind: UNIT
    DependsOn:
      - ApilambdaDatasource2C776EE2
      - ApiSchema510EECD7
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/Api/MutationdeleteLessonResolver/Resource
  AppSyncCoursesHandlerServiceRoleC7143C9A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/AppSyncCoursesHandler/ServiceRole/Resource
  AppSyncCoursesHandlerServiceRoleDefaultPolicy15319F5C:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: dynamodb:*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - CDKUserTableF87A964C
                  - Arn
              - Ref: AWS::NoValue
          - Action: dynamodb:*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - CDKQuestTable50AB07C6
                  - Arn
              - Ref: AWS::NoValue
          - Action: dynamodb:*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - CDKLessonTable59BC3444
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: AppSyncCoursesHandlerServiceRoleDefaultPolicy15319F5C
      Roles:
        - Ref: AppSyncCoursesHandlerServiceRoleC7143C9A
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/AppSyncCoursesHandler/ServiceRole/DefaultPolicy/Resource
  AppSyncCoursesHandlerE55512B6:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters057896721966991e67fc6ba33966403f5b3c16bf1a664f040866954af36fbc20S3Bucket8249A0A0
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters057896721966991e67fc6ba33966403f5b3c16bf1a664f040866954af36fbc20S3VersionKey263DDEAF
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters057896721966991e67fc6ba33966403f5b3c16bf1a664f040866954af36fbc20S3VersionKey263DDEAF
      Handler: main.handler
      Role:
        Fn::GetAtt:
          - AppSyncCoursesHandlerServiceRoleC7143C9A
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          USER_TABLE:
            Ref: CDKUserTableF87A964C
          QUEST_TABLE:
            Ref: CDKQuestTable50AB07C6
          LESSON_TABLE:
            Ref: CDKLessonTable59BC3444
      MemorySize: 1024
    DependsOn:
      - AppSyncCoursesHandlerServiceRoleDefaultPolicy15319F5C
      - AppSyncCoursesHandlerServiceRoleC7143C9A
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/AppSyncCoursesHandler/Resource
      aws:asset:path: asset.057896721966991e67fc6ba33966403f5b3c16bf1a664f040866954af36fbc20
      aws:asset:property: Code
  CDKUserTableF87A964C:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/CDKUserTable/Resource
  CDKQuestTable50AB07C6:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/CDKQuestTable/Resource
  CDKLessonTable59BC3444:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/CDKLessonTable/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.79.0,@aws-cdk/assets=1.80.0,@aws-cdk/aws-applicationautoscaling=1.80.0,@aws-cdk/aws-appsync=1.80.0,@aws-cdk/aws-autoscaling-common=1.80.0,@aws-cdk/aws-cloudwatch=1.80.0,@aws-cdk/aws-codeguruprofiler=1.80.0,@aws-cdk/aws-cognito=1.80.0,@aws-cdk/aws-dynamodb=1.80.0,@aws-cdk/aws-ec2=1.80.0,@aws-cdk/aws-ecr=1.80.0,@aws-cdk/aws-ecr-assets=1.80.0,@aws-cdk/aws-events=1.80.0,@aws-cdk/aws-iam=1.80.0,@aws-cdk/aws-kms=1.80.0,@aws-cdk/aws-lambda=1.80.0,@aws-cdk/aws-logs=1.80.0,@aws-cdk/aws-s3=1.80.0,@aws-cdk/aws-s3-assets=1.80.0,@aws-cdk/aws-sqs=1.80.0,@aws-cdk/aws-ssm=1.80.0,@aws-cdk/cloud-assembly-schema=1.80.0,@aws-cdk/core=1.80.0,@aws-cdk/custom-resources=1.80.0,@aws-cdk/cx-api=1.80.0,@aws-cdk/region-info=1.80.0,jsii-runtime=node.js/v14.13.1
    Metadata:
      aws:cdk:path: CdkAppsyncCognitoDynamodbStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  UserPoolId:
    Value:
      Ref: coursesappuserpool6C3C8587
  UserPoolClientId:
    Value:
      Ref: UserPoolClient2F5918F7
  GraphQLAPIURL:
    Value:
      Fn::GetAtt:
        - ApiF70053CD
        - GraphQLUrl
  GraphQLAPIKey:
    Value: ""
  StackRegion:
    Value:
      Ref: AWS::Region
Parameters:
  AssetParameters057896721966991e67fc6ba33966403f5b3c16bf1a664f040866954af36fbc20S3Bucket8249A0A0:
    Type: String
    Description: S3 bucket for asset "057896721966991e67fc6ba33966403f5b3c16bf1a664f040866954af36fbc20"
  AssetParameters057896721966991e67fc6ba33966403f5b3c16bf1a664f040866954af36fbc20S3VersionKey263DDEAF:
    Type: String
    Description: S3 key for asset version "057896721966991e67fc6ba33966403f5b3c16bf1a664f040866954af36fbc20"
  AssetParameters057896721966991e67fc6ba33966403f5b3c16bf1a664f040866954af36fbc20ArtifactHashE62E0CA5:
    Type: String
    Description: Artifact hash for asset "057896721966991e67fc6ba33966403f5b3c16bf1a664f040866954af36fbc20"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

```
